service: qwik-lambda-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  memorySize: 256
  timeout: 30
  stage: dev
  environment:
    DOMAIN_NAME_PARAMETER_PATH: ${env:DOMAIN_NAME_PARAMETER_PATH}

functions:
  qwik:
    handler: server/entry_aws-lambda.qwikApp
    events:
      - httpApi: "*"

custom:
  serverless-offline:
    httpPort: 4000

package:
  excludeDevDependencies: true
  patterns:
    - "!*"
    - "!*/**"
    - "server/**"
    - "dist/**"

plugins:
  - serverless-offline
